# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "IEEE UCR"
license = "GPLv3"
licenselink = "https://github.com/ieee-ucr/web-projects/blob/master/LICENSE"
description = ""
homepage = "http://ieeeucr.org/"
tags = []
features = []
min_version = "0.30"

[author]
  name = "Joel Gomez"
  homepage = "https://joelgomez.me"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
