baseURL = "http://projects.ieeeucr.org/"
languageCode = "en-us"
title = "UCR Projects"
enableGitInfo = true
[taxonomies]
    tag = "tags"
    category = "categories"
    student = "students"
    bounty = "bounties"
    post = "posts"
    course = "courses"
[params]
    description = "UCR Student Projects, hosted by IEEE-UCR."
    primaryColor = "#F44336"
    secondaryColor = "#2196F3"
